image: bigomics/omicsplayground:v2.8.12

tasks:
  - command: R -e "shiny::runApp(launch.browser=TRUE)"

ports:
  - port: 3838
    onOpen: open-browser
    
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
